Repository desujoy/kushiro, pull requests merged in 2025-01, with the labels that each got.

#38 feat : added cronjob to keep server active
  index.js
  package-lock.json
  package.json
Labels: INTERMEDIATE, SWOC

#44 [FEAT]: added a 404 page
  index.js
  public/css/style.css
  views/404.ejs
Labels: INTERMEDIATE, SWOC

#46 [FEAT] : added contributors hall of fame
  index.js
  public/css/style.css
  views/contributors.ejs
Labels: ADVANCE, SWOC

#47 added assets and improved the ui
  README.md
  public/assets/Kushiro.png
  public/assets/Kushiro.svg
  public/assets/desktop.png
  public/assets/github.png
  public/assets/icon.svg
  public/assets/linkedin.png
  public/assets/mobile.png
  public/assets/twitter.png
  public/css/style.css
  public/js/main.js
  views/footer.ejs
  views/header.ejs
Labels: INTERMEDIATE, SWOC

#52 Added contributers list
  README.md
Labels: BEGINNER, SWOC

#60 Added Random Manga Feature
  index.js
  views/header.ejs
  views/index.ejs
Labels: ADVANCE, SWOC

#59 Added Dark Mode Feature for Kushiro and Replaced PNGs with SVGs
  public/css/style.css
  views/footer.ejs
  views/header.ejs
Labels: INTERMEDIATE, SWOC

#65 Feature: Added Templates and Related Files
  .github/ISSUE_TEMPLATE/01-bug.yml
  .github/ISSUE_TEMPLATE/02-feature.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/PULL_REQUEST_TEMPLATE.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  LICENSE
  README.md
Labels: INTERMEDIATE, SWOC

#67 Fix/navbar
  public/css/style.css
Labels: BEGINNER, SWOC

#64 Added missing Favicon
  package-lock.json
  package.json
  public/manifest.json
  views/header.ejs
Labels: BEGINNER, SWOC

#70 Fixed Overlapping Issue on Contributors Page
  public/css/style.css
Labels: BEGINNER, SWOC

#73 fixed: update footer icon color for better visibility
  public/css/style.css
Labels: BEGINNER, SWOC

#71 Added testimonial
  index.js
  models/testimonial.js
  package-lock.json
  package.json
  public/css/style.css
  public/vendor/fontawesome/css/all.min.css
  public/vendor/fontawesome/webfonts/fa-solid-900.ttf
  public/vendor/fontawesome/webfonts/fa-solid-900.woff2
  sample.env
  views/footer.ejs
  views/header.ejs
  views/index.ejs
  views/testimonials.ejs
Labels: ADVANCE, SWOC

#77 fix: update copyright box font family and size for consistency
  public/css/style.css
Labels: BEGINNER, SWOC
